### ISSUE TITLE
Notice: Undefined variable: captchadir in /site/modules/DiceCaptcha/DiceCaptcha/DiceCaptcha.module 

### ISSUE THREAD

**Issue by adrianbj** [romanseidl/dice-captcha#2]
That's it really. Just needs to be defined so this error doesn't show if the config settings aren't saved.

**Comment by romanseidl** [comment]
I don't really get that.

init() does:
$this->$captchadir = $this->config->paths->assets . self::CAPTCHA_DIR;

So why should the captchadir be possibly not set? There is (yet) no config option for that.

Do you have a line number?

**Comment by adrianbj** [comment]
Ah right - sorry, I didn't actually look, just assumed. To fix the issue you should change all instances of:

```
$this->$captchadir
```

to:

```
$this->captchadir
```

**Comment by romanseidl** [comment]
Oh. How I hate those php typos. 

Will do. Thx.

**Comment by romanseidl** [comment]
changed it in the repository.
